[package]
name = "ledger-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
csv = "1.3"
quick-xml = "0.38.3"
chrono = { version = "0.4.42", features = ["serde"] }

[dev-dependencies]
serde_json = "1.0"
